import {
    Apple,
    Wallet,
    Banknote,
    HandCoins,
    ShoppingCart,
    Utensils,
    Car,
    Bus,
    Plane,
    House,
    Home,
    HeartPulse,
    Pill,
    Gamepad2,
    Film,
    Music,
    Smartphone,
    Laptop,
    Shirt,
    Gift,
    Coffee,
    BookOpen,
    GraduationCap,
    Dumbbell,
    Briefcase,
    PiggyBank,
    CreditCard,
    CircleDollarSign,
    TrendingUp,
    TrendingDown,
    Receipt,
    BadgeDollarSign,
    PlusCircle,
    Calendar,
    BarChart3,
    LogOut,
    HatGlasses 
} from 'lucide-react';

export const icons = {
    apple: Apple,
    wallet: Wallet,
    banknote: Banknote,
    handCoins: HandCoins,
    shoppingCart: ShoppingCart,
    utensils: Utensils,
    car: Car,
    bus: Bus,
    plane: Plane,
    house: House,
    home: Home,
    heartPulse: HeartPulse,
    pill: Pill,
    gamepad2: Gamepad2,
    film: Film,
    music: Music,
    smartphone: Smartphone,
    laptop: Laptop,
    shirt: Shirt,
    gift: Gift,
    coffee: Coffee,
    bookOpen: BookOpen,
    graduationCap: GraduationCap,
    dumbbell: Dumbbell,
    briefcase: Briefcase,
    piggyBank: PiggyBank,
    creditCard: CreditCard,
    circleDollarSign: CircleDollarSign,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    receipt: Receipt,
    badgeDollarSign: BadgeDollarSign,
    plusCircle: PlusCircle,
    calendar: Calendar,
    barChart3: BarChart3,
    logOut: LogOut,
    hatGlasses: HatGlasses
};